radix-ui/website

pages/primitives/docs/components/collection.mdx, pages/primitives/docs/components/context-menu.mdx, pages/primitives/docs/components/dismissable-layer.mdx, pages/primitives/docs/components/dropdown-menu.mdx, pages/primitives/docs/components/focus-scope.mdx, pages/primitives/docs/components/menu.mdx, pages/primitives/docs/components/popper.mdx, pages/primitives/docs/components/scroll-area.mdx, pages/primitives/docs/components/select.mdx, pages/primitives/docs/components/switch.mdx, pages/primitives/docs/components/toggle-button.mdx, pages/primitives/docs/components/tooltip.mdx, pages/primitives/docs/components/visually-hidden.mdx
No need to document these low-level ones for now, they are used within primitives but not really public facing.
Removed:
- `Collection`
- `DismissableLayer`
- `FocusScope`
- `Menu`
- `Popper`
Added:
- `ContextMenu`
- `DropdownMenu`
- `ScrollArea`
- `Switch`
- `ToggleButton`
- `Tooltip`
- `VisuallyHidden`
=> Remove non public-facing primitives (yet at least), and add missing ones

components/KeyboardTable.tsx, components/PropsTable.tsx, components/RegionTable.tsx
This change mirrors changes I made in the Primitive docs to improve accessibility of tables.
- A table gets a focusable wrapper marked as a `region` with an accessible name
- The wrapper allows for horizontal overflow to better support small screens and zoom settings
- When there is an overflow, the wrapper having focus allows keyboard scrolling to see the parts of the table that are cut off
=> Add focusable region wrapper with allowable overflow

.gitignore, .vscode/settings.json
I think it's generally a good idea to ignore these files, as it's hard to have your own local preferences when we include them. We do already in the primitives repo.
@peduarte calling this to your attention, as it may be important to add back to your local configuration if we're good with taking this out.
=> Ignore editor preferences

pages/primitives/docs/overview/accessibility.mdx, pages/primitives/docs/overview/animation.mdx, pages/primitives/docs/overview/styling.mdx
I just spent some time reading more closely through these pages now that I've managed to calm down a bit from the rush 😅 
Spotted a few bits.
- Missing a `c` in the word `can`
- Turns out @chaance likes the word "certain" teehee 😉  It was noticeably used quite a bit on the accessibility page so I tried to reduce its usage.
- The `forceMount` prop wasn't on the right elements in the Animation page.
=> Overview proof reading tweaks

layouts/DocsLayout.tsx, package.json
Fixes #64 by adding the helper class from [react-remove-scroll](https://github.com/theKashey/react-remove-scroll#positionfixed-elements) designed to deal with `position: fixed` elements when `right` is set to `0`.
=> Fix scrollbar jank on QuickNav (#64)

pages/primitives/docs/components/alert-dialog.mdx
Causes 'View Source' hyperlink to 404
=> Fixed typo in alert-dialog name

pages/primitives/docs/components/context-menu.mdx, pages/primitives/docs/components/dropdown-menu.mdx
I wired the `onSelect` prop on menu item in all examples as it's a basic thing and I saw some users using `onClick`. I figured it would be good to include it in the examples as that's what most people will refer to.
=> Add `onSelect` prop to menu items examples

pages/primitives/docs/components/tooltip.mdx
URL: https://radix-ui.com/primitives/docs/components/tooltip#anatomy
I copy pasted from the example and was confused why it isn't working 😅
=> Tooltip docs: Fix import statement

pages/primitives/docs/components/dialog.mdx
The default export here isn't working for me. The later docs show a Dialog.Root, which is working. Maybe a change that didn't make its way back into the first example?
=> Fix missing Dialog.Root in docs.

pages/primitives/docs/components/dropdown-menu.mdx
The documentation did not reflect the [correct default value](https://github.com/radix-ui/primitives/blob/main/packages/react/dropdown-menu/src/DropdownMenu.tsx#L116) for the `disableOutsidePointerEvents` prop. Let me know if I should also change the description to explain what happens if you set it to false, even thou I think it's quite self explanatory.
=> docs: Update disableOutsidePointerEvents default value

components/RegionTable.tsx
Table layout shenanigans cause horizontal scroll on smaller viewports. This PR introduces a workaround for this bug.
To test, open about any component page on mobile and try to scroll horizontally.
=> Fix horizontal scroll on mobile

pages/primitives/docs/overview/animation.mdx
Removes a paragraph from the Animation docs. This sentence always threw me off when I read this copy, not entirely sure what it means so I've had a go at simplifying to reduce cognitive load.
=> Simplify Animation intro copy

pages/primitives/docs/components/tooltip/0.0.1/index.mdx, pages/primitives/docs/components/tooltip/0.0.2/index.mdx, pages/primitives/docs/components/tooltip/0.0.3/index.mdx, pages/primitives/docs/components/tooltip/0.0.4/index.mdx, pages/primitives/docs/components/tooltip/0.0.5/index.mdx, pages/primitives/docs/components/tooltip/0.0.6/index.mdx, pages/primitives/docs/components/tooltip/0.0.7/index.mdx, pages/primitives/docs/components/tooltip/0.0.8/index.mdx, pages/primitives/docs/utilities/slot/0.0.1/index.mdx, pages/primitives/docs/utilities/slot/0.0.2/index.mdx, pages/primitives/docs/utilities/slot/0.0.3/index.mdx, pages/primitives/docs/utilities/slot/0.0.4/index.mdx
I noticed some of the code examples on `Tooltip` and `Slot` were using the old APIs.
=> [Tooltip][Slot] Rename props prefixed with `is`

pages/primitives/docs/overview/styling.mdx
Updates styling docs to expose `extendPrimitive` utility that consumers can use for easily adding default props to our primitives (including default `as` prop that maintains polymorphism).
=> Add `extendPrimitive` to styling

pages/primitives/docs/components/accordion/0.0.7/index.mdx
Tiny fix to accordion example code.
=> Missing slash in accordion docs.

layouts/DocsLayout.tsx
After chatting with Colm, we decided on a slightly different way to the releases/changelog/history.
This change is something we worked out on the call together.
=> Show what is "latest" version

pages/primitives/docs/components/toggle/0.0.1/index.mdx, pages/primitives/docs/components/toggle/0.0.5/index.mdx, types/index.ts, utils/primitives.ts
This PR re-instates the history of `Toggle` by adding the `ToggleButton` docs inside it as the package was renamed.
Everything works well, the only thing that was needed was to add a frontmatter metadata to hide some components from the nav as we do not want to see both `Toggle` and `ToggleButton` entries, but instead of we find `ToggleButton` old versions under the now latest `Toggle`.
=> Re-instate old `ToggleButton` docs under `Toggle`

components/DesignSystemPage.tsx, data/design-system/docs/components/button/0.0.1.mdx, data/design-system/docs/overview/introduction.mdx, lib/designSystemRoutes.ts, lib/primitivesRoutes.ts, next.config.js, pages/_app.tsx, pages/design-system/docs/components/[...slug].tsx, pages/design-system/docs/overview/[slug].tsx
This PR adds support for design system docs
ATM it works exactly the same as the primitive docs. I've duplicated everything so we can make changes to each docs independently without worrying about abstractions
https://website-git-design-system-docs-radix-ui.vercel.app/design-system/docs/overview/introduction
=> Add design-system docs

components/PropsTable.tsx
Not sure when this happened but I noticed the popover for the "full" type in our props tables was not visible.
It seems it would have been since an update of stitches as the breakpoint syntax as changed.
I've also tweaked some CSS as I think a DS update came with a `maxWidth: 256` for `PopoverContent` but for those types they don't wrap so they need to extend to the content. Also removed the hardcoded height, not sure why it was there in the first place…
=> Fix missing "full" type popover

data/primitives/components/radio-group/0.0.16.mdx
The name prop is no longer necessary as the name is propagated from the RadioGroup.Root component as explained by @benoitgrelard  in this [closed issue](https://github.com/radix-ui/primitives/issues/655)
=> [RadioGroup] Remove name from PropsTable

data/primitives/components/radio-group/0.0.1.mdx, data/primitives/components/radio-group/0.0.14.mdx, data/primitives/components/radio-group/0.0.16.mdx, data/primitives/components/radio-group/0.0.6.mdx
The `name` prop was removed from `Item` in #162 which is correct, but it seems it was never added to `Root` (was never moved back then basically).
=> Further fixes to RadioGroup docs

data/primitives/utilities/polymorphic/0.0.11.mdx
Updates polymorphic docs to remove type casting recommendation. It seems some of the changes I've been making recently have meant we no longer need to cast. 
This approach will hopefully feel more natural to consumers as people tend to prefer to avoid casting.
Thanks @benoitgrelard for pointing out that we can do this without issue.
=> Remove casting from polymorphic types

data/primitives/components/scroll-area/0.0.13.mdx
this pr fixes a tiny typo in the features list for the scrollarea component.
=> fix scrollarea features typo

data/primitives/components/context-menu/0.0.21.mdx, data/primitives/components/dropdown-menu/0.0.20.mdx
Corrects missing `StyledSeparator` in original submenu examples.
=> [DropdownMenu][ContextMenu] Add missing `StyledSeparator` to examples

data/primitives/components/scroll-area/0.0.14.mdx
=> Fix typo in ScrollArea scrollbar property description

data/primitives/utilities/polymorphic/0.0.12.mdx
Removes an extra angle bracket from the polymorphic primitive basic example, which causes a typescript error when copy-pasted directly into an editor.
=> Remove extra angle bracket from polymorphic primitive basic example

data/colors/getting-started/usage.mdx
I've noticed that vanilla CSS example was missing `@` at the beginning of import.
=> Fix imports in vanilla CSS example

data/colors/getting-started/usage.mdx
Got an error on Radix Colors usage stitches example because the import was missing the `yellow` import to spread on stitches colors object. So I Added yellow import missing on stitches usage.
=> Typo on Radix Colors usage on site

data/primitives/overview/styling.mdx
`polymoprhism` to `polymorphism`.
=> Primitives – Fix typo on styling page

data/primitives/components/context-menu/0.0.1.mdx, data/primitives/components/context-menu/0.0.17.mdx, data/primitives/components/context-menu/0.0.19.mdx, data/primitives/components/context-menu/0.0.22.mdx, data/primitives/components/context-menu/0.0.23.mdx, data/primitives/components/context-menu/0.0.24.mdx, data/primitives/components/context-menu/0.0.7.mdx, data/primitives/components/context-menu/0.0.8.mdx, data/primitives/components/dropdown-menu/0.0.1.mdx, data/primitives/components/dropdown-menu/0.0.17.mdx, data/primitives/components/dropdown-menu/0.0.19.mdx, data/primitives/components/dropdown-menu/0.0.22.mdx, data/primitives/components/dropdown-menu/0.0.23.mdx, data/primitives/components/dropdown-menu/0.0.7.mdx, data/primitives/components/dropdown-menu/0.0.8.mdx, data/primitives/components/hover-card/0.0.4.mdx, data/primitives/components/popover/0.0.1.mdx, data/primitives/components/popover/0.0.15.mdx, data/primitives/components/popover/0.0.17.mdx, data/primitives/components/popover/0.0.19.mdx, data/primitives/components/popover/0.0.20.mdx, data/primitives/components/popover/0.0.6.mdx, data/primitives/components/tooltip/0.0.1.mdx, data/primitives/components/tooltip/0.0.16.mdx, data/primitives/components/tooltip/0.0.21.mdx, data/primitives/components/tooltip/0.0.3.mdx, data/primitives/components/tooltip/0.0.7.mdx, data/primitives/components/tooltip/0.0.9.mdx
`collisionTolerance` should be type `number`, not `boolean` in the docs.
=> [Primitives docs] Change `collisionTolerance` prop type to `number`

data/primitives/components/accordion/0.1.0.mdx, data/primitives/components/alert-dialog/0.1.0.mdx, data/primitives/components/aspect-ratio/0.1.0.mdx, data/primitives/components/avatar/0.1.0.mdx, data/primitives/components/checkbox/0.1.0.mdx, data/primitives/components/collapsible/0.1.0.mdx, data/primitives/components/context-menu/0.1.0.mdx, data/primitives/components/dialog/0.1.0.mdx, data/primitives/components/dropdown-menu/0.1.0.mdx, data/primitives/components/hover-card/0.1.0.mdx, data/primitives/components/label/0.1.0.mdx, data/primitives/components/popover/0.1.0.mdx, data/primitives/components/progress/0.1.0.mdx, data/primitives/components/radio-group/0.1.0.mdx, data/primitives/components/scroll-area/0.1.0.mdx, data/primitives/components/separator/0.1.0.mdx, data/primitives/components/slider/0.1.0.mdx, data/primitives/components/switch/0.1.0.mdx, data/primitives/components/tabs/0.1.0.mdx, data/primitives/components/toggle-group/0.1.0.mdx, data/primitives/components/toggle/0.1.0.mdx, data/primitives/components/toolbar/0.1.0.mdx, data/primitives/components/tooltip/0.1.0.mdx, data/primitives/overview/introduction.mdx, data/primitives/overview/styling.mdx, data/primitives/utilities/announce/0.1.0.mdx, data/primitives/utilities/visually-hidden/0.1.0.mdx
This PR updates the copy of the main pages as well as the change from `as` to `asChild` in props tables.
=> Beta copy + `as` -> `asChild` props tables 

data/colors/getting-started/aliasing.mdx
The documentation mentioned 1 step below the correct ones, 9 is for solid backgrounds and 8 for hovered component borders.
This pull request fixes this typo. 
https://www.radix-ui.com/docs/colors/getting-started/aliasing#use-case-aliases
=> [Colors docs] Fix typos in Aliasing ## Use case aliases

data/colors/getting-started/usage.mdx
Hi,
this PR updates the usage documentation (https://www.radix-ui.com/docs/colors/getting-started/usage) to work with the most current version of stitches.
https://github.com/modulz/stitches/issues/682
=> Replace createCss with the current createStitches

components/marketing/MainHero.tsx
- Improve roving keyboard navigation on the carousel
- Add Esc key to exit a demo (press Enter to enter a demo when focused)
- Add aria labels for demos
- I still want to do a few related improvements to make the demo experience nice for screen reader users; will figure it out in the next iteration.
- Fix miscellaneous related bugs
- (Unrelated) Fix slightly clipped “Why waste…” heading letters
=> Main hero — keyboard navigation improvements

components/DocCodeBlock.tsx
We had reports of type errors in our demos
I'm still investigating but nothing changed on our end AFAIK, for now I've found adding `react-scripts` as a dependency to the generated sandbox resolves the issue.
=> Fix sandbox type error

components/ColorTestSaturationDark.tsx
Column heading for column "12" was incorrectly set to "11". This commit set it to "12" ✌️
| Before | After |
| ------ | ------|
| <img width="953" alt="2021-11-20 at 15 20 45 CleanShot@2x" src="https://user-images.githubusercontent.com/2470775/142729699-d23bcec2-1bb1-4408-9a60-164fc07bbe09.png">       |    <img width="953" alt="2021-11-20 at 15 20 14 CleanShot@2x" src="https://user-images.githubusercontent.com/2470775/142729704-eb778edd-e942-4901-83aa-bfcb1289ed83.png">   |
| https://www.radix-ui.com/docs/colors/tests/balance#steps-712-1 | https://radix-website-git-fork-rix1-patch-1.modulz-deploys.com/docs/colors/tests/balance#steps-712-1 |
=> @radix-ui/colors: Fix column index issue for ColorTestSaturationDark

components/DocCodeBlock.tsx
Original fix https://github.com/radix-ui/website/pull/276 should have added this as `devDependencies`
CSB came back with the same solution
> The sandbox didn't have react-scripts installed, which made our detection logic think that you were on react-scripts v1, which imports .cjs files as raw files. If you add react-scripts v4 to your devDependencies, we'll use the latest version of react-scripts, and it will work.
When asking about the reason this requirement would have changed:
> We did recently change our resolver logic, and we resolved the .cjs file instead of the .mjs file. That's the only thing that could explain it (I think).
=> [Sandbox demos] Move react-scripts to dev dependencies

data/primitives/overview/releases.mdx
I'd copy/pasted a note about converting the `Dropdown.Trigger` to a `button` but the `Dropdown.Trigger` was always a button, we just updated its logic to use `onClick` in that case instead of `onKeyDown`.
=> [Release] Remove redundant changelog item

components/Header.tsx
^ Vercel bot will be a good soldier and add it for us
=========================================
react-remove-scroll expects you to add some classes to the containers potentially pushed around by the "removal" of the scrollbar, this PR adds it to the header (the body and quick nav already have what they need to not shift around)
=========================================
=> [website] Prevent header shifting while scrolllocking

data/primitives/components/accordion/0.1.5.mdx, data/primitives/components/collapsible/0.1.5.mdx
An issue was raised in our Discord about content height animation not working and these examples were copy/pasted as a base.
It does work but the example styles look broken so I've improved them.
=> [Accordion][Collapsible] Improve copy/pastability for height anim examples

components/PrimitivesPage.tsx
Fix issue where inner docs stacking would bleed and compete with the site nav.
=> Contain docs page stacking context

components/marketing/MainHero.tsx
👋 hi! big fan of Radix and was poking around the source code, just noticed that the aria labels are swapped on the home page carousel previous/next buttons and figured I'd open a quick PR in case no one's caught it yet
- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Fixes a bug
=> fix aria-labels on Carousel Previous/Next buttons

data/primitives/components/select/0.1.2.mdx, data/primitives/overview/releases.mdx
> Note: I haven't documented the data attributes in the page as I assume we'll do this globally when we tackle #224
=> Document latest menu/select updates

data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1401
=> Document DismissableLayer fixes

data/primitives/components/tabs/0.2.0.mdx, data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1346
Actual change https://github.com/radix-ui/website/commit/438d239d688e5ead6b113d0a2a222b57436ef5c6
=> Document tabs animation

data/primitives/components/hover-card/0.1.5.mdx
Changed the example's `delayDuration` prop to `openDelay` to match the API
=> [HoverCard] Fix incorrect prop name in example

data/primitives/components/toast/0.1.1.mdx
Noticed this was missing from the original documentation
=> [Toast] Document label prop on provider

data/primitives/components/toast/0.1.1.mdx, data/primitives/components/toast/1.0.0.mdx
closes https://github.com/radix-ui/website/issues/445
=> Add missing event props to `Toast.Root`

data/primitives/components/toolbar/1.0.0.mdx
Adds the (I think missing) `data-state` `"on" | "off"` reference to the Toolbar ToggleItem documentation.
=> Add missing data-state to Toolbar component

algolia/config.json, components/PrimitivesDocsSearch.tsx
Seems we need to do a bit more work with the URLs returned from Algolia as prefetching in production isn't working at the moment, they return 404s and the behaviour is falling back to absolute routing anyway.
Will look into it separately for now this should silence the console.
=> [Search] Temporarily remove next link prefetch

data/primitives/components/context-menu/1.0.0.mdx
Fix small typo in context menu documentation
=> Fix wrong casing in context menu docs

data/primitives/components/alert-dialog/1.0.0.mdx
Add an example of "Close after asynchronous form submission" to Alert Dialog page. It's copied from Dialog example with some changes.
=> [Alert Dialog] Add close after async form submission example

data/primitives/components/select/1.1.0.mdx, data/primitives/overview/releases.mdx
Document the `disabled` prop in API Reference (Merge after [this PR](https://github.com/radix-ui/primitives/pull/1699) merged)
=> [Select] Add `disabled` to API Reference

data/primitives/components/context-menu/1.0.0.mdx, data/primitives/components/context-menu/2.0.0.mdx, data/primitives/components/dropdown-menu/1.0.0.mdx, data/primitives/components/dropdown-menu/2.0.0.mdx, data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1624
Changelog entry: https://github.com/radix-ui/website/pull/493/commits/b6669c8143d383c814a67b58f727194e806214d8
Docs changes: https://github.com/radix-ui/website/pull/493/commits/9969dd63445ef73627341fe5671879b05d45c249
=> Document latest `DropdownMenu`/`ContextMenu` changes (`CheckboxItem` indeterminate)

components/DocsNav.tsx
I'm not sure if this is a PR that you might agree with but while navigating the website I noticed that the navigation items were very close to each other and there was an overlapping issue between the current selected item and the previous/next ones.
To prevent this I've added some spacing between items by checking if it's the last item in the section
---
**Before**
https://user-images.githubusercontent.com/30603437/195714008-4c6f650a-b07c-44cb-8613-e8299274daf0.mp4
**After**
https://user-images.githubusercontent.com/30603437/195714220-872e1949-f3bb-4722-87ec-e54048641923.mp4
---
=> Fix spacing between elements on website's nav menu

components/HeroCodeBlock.tsx, components/Select.tsx
I've added better focus accessibility by bringing it inline with what is done in the WorkOS docs, I think it works very well.
Also slightly updated the Select we use internally to bring it close with the DS ghost buttons which brings things more inline.
=> Tweak tabs UI styles

components/HeroCodeBlock.tsx
Worked with @vladmoroz to improve the accessibility/ui for collapsing/expanding the code.
=> Tweak expand UI

components/demos/Dialog/css/styles.css
Fix typo — `opacity` to `transform`.
=> Fix typo in Dialog demo CSS

data/primitives/components/alert-dialog/1.0.2.mdx, data/primitives/components/dialog/1.0.2.mdx
I've also pared down on async/await to make things simpler and not add more potential confusion.
=> [Dialog][AlertDialog] Fix async examples

components/marketing/MainHeroDropdownMenu.tsx, components/marketing/MainHeroPopover.tsx
Scrolling the homepage with a Mac touchpad would be wobble the dropdown menu and popover, which isn't really an issue when using them for real, but looks awkward on the demos.
Before:
https://user-images.githubusercontent.com/8441036/211537846-dd0cfd7e-8623-4ac6-baba-e4c1feb901f8.mov
After:
https://user-images.githubusercontent.com/8441036/211537893-e949afe5-5d41-4f00-9e09-b4956765a9e6.mov
=> Fix wobbly homepage components

components/HeroCodeBlock.tsx, components/demos/Accordion/tailwind/index.jsx, components/demos/Accordion/tailwind/tailwind.config.js, lib/constants.ts, lib/rehype-hero-code-block.ts
Some points
- I wasn't able to use `create-react-app` as template on codesandbox to run tailwindcss so I had to use `vite`. If you guys have any idea how to setup with `create-react-app` I appreciate
- I think we can put the space too that is used in demos in `tailwind.config.js`. I don't know if is too much for the user to copy?
=> [POC][Accordion] Add tailwind CSS support

components/HeroCodeBlock.tsx
This ensures if someone has selected "Tailwind CSS" in a demo (`Accordion` only now), and switches to another component which doesn't yet have a matching Tailwind demo, it falls back to the CSS one.
=> Fallback to default CSS lib example if no matching demo found

components/HeroCodeBlock.tsx
I noticed the fonts were lacking antialiasing in the Tailwind codesandbox, whereas the preview on the Radix website has it. I added this to the Tailwind config. Normally I add the Tailwind `antialiased` class directly to the body tag
=> Add antialiasing to Tailwind config

components/demos/Toolbar/css/styles.css, components/demos/Toolbar/stitches/index.jsx, components/demos/Toolbar/tailwind/index.jsx, components/demos/Toolbar/tailwind/tailwind.config.js
Added the Tailwind CSS example to the Toolbar demos. I also resolved an issue with the CSS and Stitches demo where the button had purple text on a dark purple background on hover, making it difficult to read and lacking insufficient color contrast.
=> Add Tailwind CSS demo to Toolbar

components/demos/Accordion/tailwind/index.jsx
The arbitrary value for the ease class contained spaces which caused it to be broken at build time. I replaced the spaces with underscores which fixes the problem.
https://tailwindcss.com/docs/adding-custom-styles#handling-whitespace
=> Fix Tailwind Accordion demo

components/demos/Dialog/css/index.jsx, components/demos/Dialog/stitches/index.jsx, components/demos/Dialog/tailwind/index.jsx
Remove useless `size` prop from dialog trigger from CSS and Tailwind CSS demos. I'm wondering why use `asChild` in these demos and not use `className` directly on `Dialog.Trigger`, this happens in some other components too.
=> Remove useless size prop from dialog trigger

data/primitives/components/form/0.0.2.mdx
=> Use valid value for match prop in server-side validation example

components/HeroCodeBlock.tsx, components/ScrollArea.tsx
Why I added this little piece of media query: if you go to the docs in some block of code that contains the horizontal scrollbar (e.g [navigation menu](https://www.radix-ui.com/docs/primitives/components/navigation-menu)), you will notice that it is difficult to click on the "Collapse code" button when the scrollbar is visible, to do that, you need to click in the extreme top of the button. 
In the video i'm clicking in the button and you will notice that the code don't collapse, then i'm sliding the scroll because the scroll is above the button and then i'm clicking in the top of button to collapse.
[collapse-button.webm](https://user-images.githubusercontent.com/58708551/207613977-5b23fe88-8260-452f-b21c-e1e039c9c152.webm)
I noticed that the piece of code that made this happen is the …
=> Added media query to ScrollAreaThumb in ScrollArea component

data/colors/palette-composition/the-scales.mdx, pages/colors/index.tsx
Closes #638 
- Swap Orange / Brown colors on the home page
- Swap Bronze / Gold colors on the home page
- Swap Bronze / Gold colors on the scales page
I didn't commit changes to [Lightness test Steps 1–6](https://www.radix-ui.com/docs/colors/tests/balance#steps-16) as I'm not sure if it's intentional or not. 
Feel like the colors order should match other scales on the page, though.
=> #638 Fix colors order inconsistency

data/primitives/components/toolbar/0.1.5.mdx, data/primitives/components/toolbar/1.0.4.mdx, data/primitives/components/tooltip/0.1.1.mdx, data/primitives/components/tooltip/0.1.7.mdx, data/primitives/components/tooltip/1.0.3.mdx, data/primitives/components/tooltip/1.0.6.mdx, data/primitives/overview/releases.mdx, data/primitives/utilities/polymorphic/0.0.14.mdx
It seems there is a broken link on the deprecated Polymorphic docs page in the alert that notifies the user the page has been deprecated. https://www.radix-ui.com/docs/primitives/utilities/polymorphic
This PR updates the link to the Composition page which describes the `asChild` prop in detail https://www.radix-ui.com/docs/primitives/guides/composition#composition
https://github.com/radix-ui/website/assets/8112138/f9fd7c84-6d2d-4868-b3f1-9843a520f7cd
Apologies committing this through GitHub so don't have a working local environment to record
=> Updating broken link on Polymorphic docs page

components/demos/HoverCard/css/styles.css
Add missing animations to `HoverCard` CSS example
=> Add animations to HoverCard CSS example

components/Scale.tsx
Fix incorrect format when copying colors as CSS / Sass / Less
=> Fix Copy colors as CSS button

data/themes/docs/overview/getting-started.mdx
The docs were referencing `index.css` but the file is `styles.css`
- Fixes a bug
=> Update getting-started.mdx to reference correct CSS path

components/UseCasesTable.tsx
**This pull request:**
**Description:**
Adjusts the step numbering in the Radix Colors documentation's [use cases](https://www.radix-ui.com/colors/docs/palette-composition/understanding-the-scale) table. Previously, the steps were displayed as `0-11`. This PR changes the numbering to correctly display as `1-12`.
=> Fix Step Numbering in Radix Colors Use Cases Table (`components/UseCasesTable.tsx`)

data/themes/docs/overview/getting-started.mdx
Make the `body` wrapping requirement clearer when getting started with Themes.
=> Clarify `Theme` wrapping requirements

components/ThemesDocsAssets.tsx
=> Improve Theme colors checkerboard in dark mode

components/ThemesDocsAssets.tsx, data/themes/docs/components/icon-button.mdx, data/themes/docs/theme/overview.mdx
- Link theme overview cards to relevant sections
- Add missing classic variant to some icon button examples
- Improve prop example asset responsive overflow handling
=> Improve examples, link to theme sections

data/themes/docs/theme/overview.mdx
This can be tested at https://www.radix-ui.com/themes/docs/theme/overview. 
Current behaviour: when clicking on the Radius card directs to https://www.radix-ui.com/themes/docs/theme/visual-style#panel-background.
This should instead be https://www.radix-ui.com/themes/docs/theme/visual-style#radius
=> fix: typo in docs, href points to incorrect location

package.json, yarn.lock
We were previously targeting `14.x` which Vercel deprecated support for as of today (Aug 15, 2023) causing all builds to fail.
https://vercel.com/docs/concepts/functions/serverless-functions/runtimes/node-js#node.js-version
=> Target Node 18

data/themes/docs/overview/getting-started.mdx
Fix the pnpm install command syntax.
```bash
pnpm install @radix-ui/themes
// fix it 
pnpm add @radix-ui/themes
```
=> Fix the pnpm install command syntax in docs

components/Scale.tsx
Preview URL: https://radix-website-git-fork-azuky-fix-hsla-to-alpha-workos.vercel.app/colors/docs/palette-composition/scales
If you copy the object as hex or as SVG, it now correctly copies the alpha values. Previously, these values were ignored
=> [fix] Change the regex that extracts the alpha value from 'hsla', as the previous one was not doing it correctly

components/DocsNav.tsx
This PR fixes the typo in github URL of themes, colors, primitives and others. The error happens in the mobile menu when accessing the github repos.
You can test the change in the URL below.
[Test URL](https://radix-ui-fix-url.vercel.app/)
=> fix: typo in URL of git repo, leads to 404 route

components/MagicCurtain.module.css, components/MagicCurtain.tsx
To improve the animation of the awesome MagicCurtain, I made some changes. 
I've kept the changes to a minimum, but please let me know if there's anything else.
Previously, the animation moved uniformly from right to left. I've updated it so that when you select an item to the left of the currently selected one, it animates from left to right. 
This update provides a more natural and captivating user experience.
[Preview  URL](https://radix-website-f9jclhqto-workos.vercel.app/)
| Before
| After
A big thanks to all the members of Radix!
=> Update MagicCurtain animation

data/themes/docs/overview/getting-started.mdx
Updated URLs on the link cards to match the intended destination.
For example, the `Visual style` link card should take user to `theme/visual-style` instead of `theme/dark-mode` 
=> Correct URLs mismatch in the link cards

components/demos/ContextMenu/css/index.jsx, components/demos/ContextMenu/stitches/index.jsx, components/demos/ContextMenu/tailwind/index.jsx
`Foward` to `Forward`
Preview link: https://radix-website-git-fork-andreasmcdermott-main-workos.vercel.app/primitives/docs/components/context-menu
=> Fix a typo in ContextMenu example code

data/primitives/docs/components/accordion/1.1.2.mdx
Updates accordion documentation anatomy example code.
=> Fix missing `export default` in accordion anatomy 

data/themes/docs/components/dialog.mdx
This PR fixes a typo in the Dialog docs where it said `<DialogClose>` rather than `<Dialog.Close>`
https://www.radix-ui.com/themes/docs/components/dialog
=> Fix typo in Radix Themes Dialog documentation

data/primitives/docs/components/tooltip/1.0.6.mdx
The documentation for `Tooltip` has a section [Displaying a tooltip from a disabled button](https://www.radix-ui.com/docs/primitives/components/tooltip#displaying-a-tooltip-from-a-disabled-button) which suggests that some extra actions should be taken to display tooltips for disabled buttons.
As we can see in this [sandbox](https://codesandbox.io/s/pedantic-curie-eojbiv?file=/App.js) these steps are not required and tooltips are shown for disabled buttons by default.
The issue is a follow-up to the [discussion in discord](https://discord.com/channels/752614004387610674/803656530259738674/1067059191140843540) @benoitgrelard found the PR https://github.com/radix-ui/primitives/pull/1358 that caused the change in behaviour
This PR updates the documentation to reflect those …
=> docs(tooltip) Remove "Displaying a tooltip from a disabled button" section

data/primitives/docs/utilities/slot/1.0.2.mdx
Update documentation for react-slot component, mention Slottable component and add an example for its usage.
=> docs(react-slot): mention <Slottable /> in docs add an example for its usage

components/Pre.module.css
---
This pull request addresses the issue where the highlighted line does not expand to fill the entire width when the code block overflows (#732).
[**Live URL**](https://radix-ui-website.vercel.app/) - https://radix-ui-website.vercel.app/
=> Fix: code block line highlighting (#732)

data/themes/docs/components/grid.mdx
This PR updates the Grid component documentation to include an example of how to use the `columns` prop to create a responsive grid layout. This important information was missing from the original documentation, and this update will make it clear to users how they can use the Grid component to create responsive layouts.
While using the Radix UI Themes documentation, it was not immediately clear that the Grid component supports responsive column layouts. This could lead other users to believe that this feature is not supported, potentially causing them to write more complex code or use additional libraries to achieve this functionality.
By including an example of responsive columns in the documentation, we can clearly demonstrate that this feature is supported out of the box. This will …
=> Add Responsive Columns Example to Grid Component Documentation

components/icons/SearchResults.tsx
Clicking an icon on the main page copies its svg content. However doing the same on the search results page copies the icon name as well.
Example:
Clicking on an icon on the main page:
```
<svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M9.875 7.5C9.875 8.81168 8.81168 9.875 7.5 9.875C6.18832 9.875 5.125 8.81168 5.125 7.5C5.125 6.18832 6.18832 5.125 7.5 5.125C8.81168 5.125 9.875 6.18832 9.875 7.5Z" fill="currentColor"></path>
</svg>
```
Clicking on an icon on the search results page:
```
<svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M9.875 7.5C9.875 8.81168 8.81168 9.875 7.5 9.875C6.18832 9.875 5.125 8.81168 5.125 7.5C5.125 6.18832 6.18832 5.125 7.5 …
```
=> Fix Icons search results copying the icon name

data/primitives/docs/components/hover-card/0.0.4.mdx, data/primitives/docs/components/hover-card/0.1.5.mdx, data/primitives/docs/components/hover-card/1.0.3.mdx, data/primitives/docs/components/hover-card/1.0.6.mdx
The current docs state that Hover Card only works on hover. This is no longer the case, as focus also triggers it.
=> Fix innacurate Hover Card docs

data/primitives/docs/components/accordion/0.0.18.mdx, data/primitives/docs/components/accordion/0.1.0.mdx, data/primitives/docs/components/accordion/1.0.2.mdx
Hi, just a minor doc fix, it was missing the `export default` in the Anatomy section of the Accordion doc
=> Fix missing export in Accordion doc anatomy section

components/demos/Accordion/tailwind/tailwind.config.js, components/demos/AlertDialog/tailwind/tailwind.config.js, components/demos/Dialog/tailwind/tailwind.config.js, components/demos/DropdownMenu/tailwind/tailwind.config.js, components/demos/HoverCard/tailwind/tailwind.config.js, components/demos/NavigationMenu/tailwind/tailwind.config.js, components/demos/Popover/tailwind/tailwind.config.js, components/demos/Toast/tailwind/tailwind.config.js, components/demos/Tooltip/tailwind/tailwind.config.js
fixes error thrown by typescript when using with `tailwind.config.ts` as it expects a string instead of number.
preview: https://radix-website-git-fork-ericreinheart-patch-1-workos.vercel.app/primitives/docs/components/toast
=> Fix Toast example with tailwindcss

data/primitives/docs/components/toast/0.1.1.mdx, data/primitives/docs/components/toast/1.0.0.mdx, data/primitives/docs/components/toast/1.1.4.mdx, data/primitives/docs/components/toast/1.1.5.mdx
The TS types have `onSwipeCancel` event but the documentation doesn't:
Code:
Docs:
=> Add `onSwipeCancel` prop documentation to `<Toast.Root />`

data/primitives/docs/components/navigation-menu/1.1.3.mdx
Fix example to reflects Next.js v13 changes.
Next Link requires a `legacyBehavior` attribute when rendering custom `<a>` markup. [cf Next.js doc](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag)
- Fixes #563
- Repo to see change can be found [here](https://github.com/damiencornu/radix-next-navigationmenu-update)
=> Update `Navigation Menu • With client side routing` example

components/generateRadixColors.tsx, data/colors/docs/overview/custom-palettes.mdx, data/colors/docs/palette-composition/understanding-the-scale.mdx, data/themes/docs/theme/color.mdx, pages/colors/custom.tsx, utils/colorsRoutes.ts
- Use percentage for OKLCH string lightness (https://github.com/radix-ui/themes/issues/420)
- Add a guide on custom palettes
- Add a more prominent theme toggle
- Discard local storage values that are older than 2 hours
=> Color generator fast follow-ups

data/themes/docs/components/text-area.mdx
Fixes a small typo `ore` → `or` in `text-area.mdx`.
=> fix(docs): small typo in text-area.mdx

components/Header.tsx
###Description
Fixes the bug: [radix-ui/website#786](https://github.com/radix-ui/website/issues/786)
This PR fixes a bug where the GitHub link had an empty accessibility name. The change adds an `aria-label` attribute to the link, as "View GitHub".
###Test Link
https://radix-website-git-fork-damyantjain-github-accessibility-workos.vercel.app/
=> Add accessibility name to github link in header

components/PrimitivesSearchDesktop.tsx
Added support for `ctrl/cmd + k` keyboard support for opening the search dialog in the primitives docs (https://www.radix-ui.com/primitives/docs/overview/introduction). This is probably the most common keyboard shortcut on most doc sites.
=> Add `ctrl/cmd + k` Keyboard Shortcut

data/primitives/docs/components/form/0.1.0.mdx
[Providing your own validation messages](https://www.radix-ui.com/primitives/docs/components/form#providing-your-own-validation-messages) and [Server-side validation](https://www.radix-ui.com/primitives/docs/components/form#server-side-validation) sections of Form documentation page have mistakes in `match` prop having incorrect `missingValue` native HTML validity state.
It should be `valueMissing` according to [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState/valueMissing).
Incorrect way:
```
<Form.Message match="missingValue" />
```
Correct way:
```
<Form.Message match="valueMissing" />
```
=> Fix "missingValue" native HTML validity state to "valueMissing"

data/primitives/docs/overview/releases.mdx
Dialog max version is 1.1.2 so the previous text saying 1.2.0 is incorrect.
Page with typo: https://www.radix-ui.com/primitives/docs/overview/releases#june-19-2024
NPM package published versions: https://www.npmjs.com/package/@radix-ui/react-dialog?activeTab=versions 
Screenshots:
=> Fix released Dialog version

data/themes/docs/components/reset.mdx
Hi team, Just a small fix to the docs. 
I noticed the link for Slot Primitive in [radix-ui / themes](https://www.radix-ui.com/themes/docs/components/reset) docs was redirecting to Portal Primitive. So I thought why not fix it :)
To replicate this issue in live:
- Go to [radix-ui](https://www.radix-ui.com/themes/docs/components/reset#api-reference) website.
- Click on Slot Primitive anchor text as shown.
- It will lead you to Portal Primitive page.
=> docs(reset): fix incorrect link for slot primitive

data/primitives/docs/utilities/slot.mdx
This pull request updates the Radix `Slot` usage in documentation and example code:
- Replaces `Root` with `Slot.Root` for clarity and correctness.
- Replaces `Slottable` with `Slot.Slottable` to match the current API.
These changes ensure proper usage of the `radix-ui` Slot API and improve consistency across examples.
You can verify the updated behavior and syntax at the following official documentation pages:
- [Slot Basic Example](https://www.radix-ui.com/primitives/docs/utilities/slot#basic-example)  
- [Slot Event Handlers](https://www.radix-ui.com/primitives/docs/utilities/slot#event-handlers)
---
=> fix(Slot): replace Slottable → Slot.Slottable, Root → Slot.Root

data/themes/docs/components/hover-card.mdx
Removes a duplicate `href` attribute from the `<Link>` element in the `HoverCard` documentation example.
**Before:**
```jsx
<Link href="#" href="https://twitter.com/radix_ui" target="_blank">
```
**After**
```jsx
<Link href="https://twitter.com/radix_ui" target="_blank">
```
Related Issue
Closes #861
Test URL
https://www.radix-ui.com/themes/docs/components/hover-card
=> fix(docs): Remove duplicate href in HoverCard example (#861)
