pages/primitives/docs/components/popover.mdx, pages/primitives/docs/components/tooltip.mdx
> Note: 🔥 Do not merge until #4 is merged, as this builds on top.
=> Tooltip props

pages/primitives/docs/components/slider.mdx
- Remove inapplicable bullet from `Slider` keyboard shortcuts 
- Update `data-*` style examples
=> `Slider` tweaks

pages/primitives/docs/components/accordion.mdx, pages/primitives/docs/components/alert-dialog.mdx, pages/primitives/docs/components/collapsible.mdx, pages/primitives/docs/components/context-menu.mdx, pages/primitives/docs/components/dialog.mdx, pages/primitives/docs/components/dropdown-menu.mdx, pages/primitives/docs/components/popover.mdx, pages/primitives/docs/components/slider.mdx, pages/primitives/docs/components/tabs.mdx, pages/primitives/docs/components/toggle-button.mdx, pages/primitives/docs/components/tooltip.mdx
Reflects changes here: https://github.com/radix-ui/primitives/pull/320
=> Update docs to reflect API consistency changes

pages/primitives/docs/overview/styling.mdx
Some copy updates to the Styling overview page.
=> Styling update

pages/primitives/docs/components/context-menu.mdx, pages/primitives/docs/components/dropdown-menu.mdx, pages/primitives/docs/components/popover.mdx, pages/primitives/docs/overview/introduction.mdx, pages/primitives/docs/utilities/portal.mdx
=> Use incorrect English

components/CodeBlock.tsx, components/DocsPage.tsx, components/ThemeToggle.tsx, pages/_app.tsx
This simply addressed the concerns raised after a quick lighthouse audit. Gonna give this a spin in VoiceOver and NVDA just to double check some things in a separate PR.
=> Initial a11y improvements

components/ExternalIcon.tsx, layouts/DocsLayout.tsx
- `dd` needs to be a direct child of `dl`
- There were instances of block elements nested in inline elements, so I cleaned those up as well
- Added accessible text to the `ExternalIcon` component since they convey meaning
=> HTML validation tweaks

pages/primitives/docs/overview/animation.mdx
I think it may have been me that stuffed this one up. Sorry ladzzzz 🙈 😅
=> Fix js animation example

components/BlogPage.tsx, components/DocsPage.tsx, components/ExternalIcon.tsx, components/Footer.tsx, components/MDXComponents.tsx, components/PropsTable.tsx, components/RadixLogo.tsx, components/ThemeToggle.tsx, layouts/BlogLayout.tsx, pages/blog/index.tsx, pages/design-system/index.tsx
@benoitgrelard This one's for you, homie
=> Use accessible-icon primitive

pages/primitives/docs/components/context-menu.mdx, pages/primitives/docs/components/dropdown-menu.mdx
=> Improve accessibility section of menu components

pages/primitives/docs/overview/accessibility.mdx
Testing:
- https://radix-ui.com/primitives/docs/overview/accessibility
=> docs: update overview/accessibility broken links.

pages/primitives/docs/components/accordion/0.0.1/index.mdx
While helping someone in Discord I realised that we hadn't documented this prop for the `AccordionPanel`.
https://radix-ui.com/primitives/docs/components/accordion
=> [Accordion] Add `forceMount` prop to `AccordionPanel`

pages/primitives/docs/components/accordion/0.0.2/index.mdx, pages/primitives/docs/components/alert-dialog/0.0.2/index.mdx, pages/primitives/docs/components/avatar/0.0.2/index.mdx, pages/primitives/docs/components/checkbox/0.0.2/index.mdx, pages/primitives/docs/components/collapsible/0.0.2/index.mdx, pages/primitives/docs/components/context-menu/0.0.2/index.mdx, pages/primitives/docs/components/dialog/0.0.2/index.mdx, pages/primitives/docs/components/dropdown-menu/0.0.2/index.mdx, pages/primitives/docs/components/popover/0.0.2/index.mdx, pages/primitives/docs/components/progress/0.0.2/index.mdx, pages/primitives/docs/components/radio-group/0.0.2/index.mdx, pages/primitives/docs/components/scroll-area/0.0.2/index.mdx, pages/primitives/docs/components/separator/0.0.2/index.mdx, pages/primitives/docs/components/slider/0.0.2/index.mdx, pages/primitives/docs/components/switch/0.0.2/index.mdx, pages/primitives/docs/components/tabs/0.0.2/index.mdx, pages/primitives/docs/components/toggle-button/0.0.2/index.mdx, pages/primitives/docs/components/tooltip/0.0.2/index.mdx, pages/primitives/docs/utilities/accessible-icon/0.0.2/index.mdx, pages/primitives/docs/utilities/announce/0.0.2/index.mdx, pages/primitives/docs/utilities/aspect-ratio/0.0.2/index.mdx, pages/primitives/docs/utilities/label/0.0.2/index.mdx, pages/primitives/docs/utilities/portal/0.0.2/index.mdx, pages/primitives/docs/utilities/visually-hidden/0.0.2/index.mdx
**NOTE: Don't merge! 👇**
I'm just duplicating the files in this PR to make reviewing the docs changes easier. 
I've created a stacked PR (#85) on top so we can review the actual relevant changes to the docs properly, otherwise it would all be new files and we wouldn't know what content has changed.
=> [release][step1] Duplicate relevant package version files

pages/primitives/docs/components/accordion/0.0.4/index.mdx, pages/primitives/docs/components/alert-dialog/0.0.5/index.mdx, pages/primitives/docs/components/avatar/0.0.4/index.mdx, pages/primitives/docs/components/checkbox/0.0.4/index.mdx, pages/primitives/docs/components/collapsible/0.0.4/index.mdx, pages/primitives/docs/components/context-menu/0.0.5/index.mdx, pages/primitives/docs/components/dialog/0.0.5/index.mdx, pages/primitives/docs/components/dropdown-menu/0.0.5/index.mdx, pages/primitives/docs/components/popover/0.0.4/index.mdx, pages/primitives/docs/components/progress/0.0.4/index.mdx, pages/primitives/docs/components/radio-group/0.0.4/index.mdx, pages/primitives/docs/components/scroll-area/0.0.4/index.mdx, pages/primitives/docs/components/separator/0.0.4/index.mdx, pages/primitives/docs/components/slider/0.0.4/index.mdx, pages/primitives/docs/components/switch/0.0.4/index.mdx, pages/primitives/docs/components/tabs/0.0.4/index.mdx, pages/primitives/docs/components/toggle-button/0.0.4/index.mdx, pages/primitives/docs/components/tooltip/0.0.4/index.mdx, pages/primitives/docs/utilities/accessible-icon/0.0.4/index.mdx, pages/primitives/docs/utilities/announce/0.0.4/index.mdx, pages/primitives/docs/utilities/aspect-ratio/0.0.4/index.mdx, pages/primitives/docs/utilities/label/0.0.4/index.mdx, pages/primitives/docs/utilities/portal/0.0.4/index.mdx, pages/primitives/docs/utilities/visually-hidden/0.0.4/index.mdx
=> [ignore] Add new folders for versions

pages/blog/introducing-radix-primitives.mdx, pages/primitives/docs/overview/introduction.mdx
I'm pretty sure that WAI-ARA is just a typo. 😀
=> Fix spelling of WAI-ARIA

pages/primitives/docs/utilities/accessible-icon/0.0.5/index.mdx
Currently, the page https://radix-ui.com/primitives/docs/utilities/accessible-icon links to https://radix-ui.com/primitives/docs/utilities/accessible-icon/visually-hidden, which is a 404
Fixed here: https://website-git-fork-lachlanjc-patch-1.radix-ui.vercel.app/primitives/docs/utilities/accessible-icon
=> Fix Accessible Icon link to Visually Hidden

pages/primitives/docs/components/context-menu/0.0.8/index.mdx, pages/primitives/docs/components/dropdown-menu/0.0.8/index.mdx
> Note: Don't merge before #97
This PR builds on #97 and adds just the changes.
=> Update docs 2

components/Select.tsx
=> Fix Select component style on Safari

pages/primitives/docs/overview/animation.mdx, pages/primitives/docs/overview/styling.mdx, pages/primitives/docs/utilities/portal/0.0.5/index.mdx
Remove `data-radix-*` references from docs where no longer relevant.
=> Update data attributes

pages/primitives/docs/components/accordion/0.0.6/index.mdx
Adds new `type` prop and examples
=> Update Accordion props and examples

pages/primitives/docs/components/accordion/0.0.7/index.mdx, pages/primitives/docs/components/collapsible/0.0.7/index.mdx
=> Add styling section to Collapsible and Accordion

pages/primitives/docs/overview/animation.mdx
=> Remove CSS transition support from animation page

pages/primitives/docs/overview/styling.mdx
=> Update `extendPrimitive` docs to match API

pages/primitives/docs/overview/styling.mdx
http://radix-ui.com/primitives/docs/overview/styling
=> [Styling] Update styling docs with wrapping examples

pages/primitives/docs/utilities/id-provider/0.0.1/index.mdx
=> Add IdProvider docs

pages/primitives/docs/components/tooltip/0.0.9/index.mdx
=> Add disabled trigger example in tooltip docs

components/Primitives.tsx, package.json, pages/primitives/docs/components/tooltip/0.0.15/index.mdx, pages/primitives/docs/components/tooltip/0.0.9/index.mdx
=> Update docs - part 2 (Custom timings on Tooltip)

components/Primitives.tsx, components/PrimitivesNav.tsx, layouts/DocsLayout.tsx, package.json, pages/primitives/docs/components/accordion/0.0.12/index.mdx, pages/primitives/docs/components/accordion/0.0.6/index.mdx, pages/primitives/docs/components/accordion/0.0.7/index.mdx, pages/primitives/docs/components/toggle-group/0.0.5/index.mdx, yarn.lock
----------
----------
This PR also update Accordion docs.
=> Update docs - part 3 (New ToggleGroup)

components/PackageRelease.tsx, layouts/DocsLayout.tsx, pages/primitives/docs/overview/releases.mdx
This includes the last 2 releases portrayed accurately, I will retroactively fill the older releases later.
=> Add new releases page

pages/primitives/docs/overview/animation.mdx
=> [Animation] fix typos

pages/_document.tsx
=> Add preload to font

data/primitives/docs/utilities/polymorphic/0.0.10.mdx, lib/docsRoutes.ts
Link to page: https://website-git-add-polymorphic-docs-radix-ui.vercel.app/primitives/docs/utilities/polymorphic
=> Add polymorphic docs

components/demos/ScrollArea.tsx, data/primitives/docs/components/scroll-area/0.0.1.mdx, data/primitives/docs/components/scroll-area/0.0.12.mdx, data/primitives/docs/components/scroll-area/0.0.5.mdx
Originally reported here: https://github.com/radix-ui/primitives/issues/637
=> Fix ScrollArea docs

data/primitives/docs/utilities/polymorphic/0.0.11.mdx
=> Fixed typo in Polymorphic docs

components/demos/Accordion.tsx, data/primitives/docs/components/accordion/0.0.15.mdx
=> Fix Accordion "Prevent close" Example

data/primitives/docs/components/popover/0.0.17.mdx
=> Fix Popover anchor example

lib/analytics.ts, package.json, pages/_document.tsx, yarn.lock
Remove Segment and using Google Analytics directly. /cc @StephenHaney
=> Remove segment

components/demos/Dialog.tsx, components/demos/ScrollArea.tsx, data/primitives/components/context-menu/0.0.23.mdx, data/primitives/components/dialog/0.0.19.mdx, data/primitives/components/scroll-area/0.0.15.mdx
This PR builds on top of the previous on #195 and now contains the actual docs changes.
=> Docs updates

data/primitives/overview/server-side-rendering.mdx
=> Fix "Gatsby" typo on server-side-rendering.mdx

data/colors/getting-started/aliasing.mdx, data/colors/getting-started/installation.mdx
=> Add version to colors installation page

data/primitives/utilities/id-provider/0.0.6.mdx
=> Fix broken SSR guide link on IdProvider page

data/colors/palette-composition/understanding-the-scale.mdx
This updates the page https://www.radix-ui.com/docs/colors/palette-composition/the-scales by replacing examples where the name of the colour is instead "Button"
=> Update examples with text of button - Colours

components/ColorTestSaturationDark.tsx, components/ColorTestSaturationLight.tsx, components/ColorTestText.tsx, components/ColorTestTextLarge.tsx
This pull request adds the Grass color scale where it was missing from the following pages:
- https://www.radix-ui.com/docs/colors/tests/balance
- https://www.radix-ui.com/docs/colors/tests/contrast
=> Colors Website - Fix Grass missing from some color tests

components/demos/HoverCard.jsx
The avatar in the hover card demo should now have `cursor: pointer` and open Twitter page in a new tab.
[Main's URL](https://www.radix-ui.com/docs/primitives/components/hover-card)
[This PR's URL](https://radix-website-git-fork-smhmd-feat-smhmdanchor-tag-fix.modulz-deploys.com/docs/primitives/components/hover-card)
Fixes #212
=> [HoverCard][Demo] Fix anchor tag in Hover Card demo

data/primitives/components/alert-dialog/0.0.20.mdx, data/primitives/components/context-menu/0.0.24.mdx, data/primitives/components/dialog/0.0.20.mdx, data/primitives/components/dropdown-menu/0.0.23.mdx, data/primitives/components/popover/0.0.20.mdx, data/primitives/utilities/polymorphic/0.0.13.mdx
Builds on https://github.com/radix-ui/website/pull/219
Second PR of a series which are going into a `release-04-08-2021` branch for docs changes.
=> Primitives release 04/08/2021 – Docs changes

data/primitives/components/context-menu/0.0.24.mdx, data/primitives/components/dialog/0.0.20.mdx, data/primitives/components/dropdown-menu/0.0.23.mdx, data/primitives/components/popover/0.0.20.mdx
=> [Primitives] Move modal props to `root`

components/PrimitivesPage.tsx, data/primitives/components/accordion/0.1.0.mdx, data/primitives/components/alert-dialog/0.1.0.mdx, data/primitives/components/aspect-ratio/0.1.0.mdx, data/primitives/components/avatar/0.1.0.mdx, data/primitives/components/checkbox/0.1.0.mdx, data/primitives/components/collapsible/0.1.0.mdx, data/primitives/components/context-menu/0.1.0.mdx, data/primitives/components/dialog/0.1.0.mdx, data/primitives/components/dropdown-menu/0.1.0.mdx, data/primitives/components/hover-card/0.1.0.mdx, data/primitives/components/label/0.1.0.mdx, data/primitives/components/popover/0.1.0.mdx, data/primitives/components/progress/0.1.0.mdx, data/primitives/components/radio-group/0.1.0.mdx, data/primitives/components/scroll-area/0.1.0.mdx, data/primitives/components/separator/0.1.0.mdx, data/primitives/components/slider/0.1.0.mdx, data/primitives/components/switch/0.1.0.mdx, data/primitives/components/tabs/0.1.0.mdx, data/primitives/components/toggle-group/0.1.0.mdx, data/primitives/components/toggle/0.1.0.mdx, data/primitives/components/toolbar/0.1.0.mdx, data/primitives/components/tooltip/0.1.0.mdx, data/primitives/utilities/accessible-icon/0.1.0.mdx, data/primitives/utilities/announce/0.1.0.mdx, data/primitives/utilities/id-provider/0.1.0.mdx, data/primitives/utilities/visually-hidden/0.1.0.mdx, lib/primitivesRoutes.ts
This PR just duplicates the files without making any changes to them yet.
The changes will come in the next PR.
> Note: This adds types for the routes and sets `Slot` and `Polymorphic` packages as deprecated.
=> Add new 0.1.0 pages

data/primitives/overview/releases.mdx
This PR adds the changelog for the beta release.
=> Add release

data/colors/palette-composition/understanding-the-scale.mdx
=> [Colors docs] Add missing backticks (`) to step number

components/demos/AlertDialog.jsx, components/demos/Dialog.jsx
closes https://github.com/radix-ui/website/issues/265
Unsure if this was originally needed for perf but it does improve the clarity quite a bit.
=> [AlertDialog][Dialog] Remove will-change from demos

data/primitives/components/context-menu/0.0.1.mdx, data/primitives/components/context-menu/0.0.17.mdx, data/primitives/components/context-menu/0.0.19.mdx, data/primitives/components/context-menu/0.0.22.mdx, data/primitives/components/context-menu/0.0.23.mdx, data/primitives/components/context-menu/0.0.24.mdx, data/primitives/components/context-menu/0.0.7.mdx, data/primitives/components/context-menu/0.0.8.mdx, data/primitives/components/context-menu/0.1.0.mdx, data/primitives/components/context-menu/0.1.1.mdx, data/primitives/components/dropdown-menu/0.0.22.mdx, data/primitives/components/dropdown-menu/0.0.23.mdx, data/primitives/components/dropdown-menu/0.1.0.mdx, data/primitives/components/dropdown-menu/0.1.1.mdx
=> Fix `DropdownMenu` keyboard docs

components/marketing/ComponentHighlightsSection.tsx
=> fix(website): Fix typo in ComponentHighlightsSection

components/marketing/MainHero.tsx
Fixes a case when the carousel may scroll unexpectedly as its slides are clicked
=> Fix scroll shift when clicking carousel slides

components/demos/Dialog.jsx, components/marketing/Carousel.tsx, components/marketing/CaseStudiesSection.tsx, components/marketing/MainHero.tsx, components/marketing/MainHeroDialog.tsx, components/marketing/StatsSection.tsx, package.json, yarn.lock
- Make the carousel draggable
- Add dialog demo (thanks @jjenzz for that portal change!)
- Add “See more components in the docs” slide
- Scroll slides into view more consistently when roving through the carousel with keyboard arrows
- Update Radix stats (@colmtuite not sure about downloads, what's the latest number?)
=> Hero carousel improvements

components/marketing/Carousel.tsx, components/marketing/MainHeroDialog.tsx, data/primitives/overview/introduction.mdx
- Fix a carousel bug when carousel arrow buttons didn't work in certain cases
- Adjust the carousel so that arrow buttons slide by one slide at a time rather than two on smaller viewports
- Fix a broken link in docs
- Update Dialog demo contents so it’s not confused with an AlertDialog
Closes #282, #283, #284
=> Carousel fixes & improvements

pages/colors/index.tsx
Closes https://github.com/radix-ui/website/issues/288
=> fix: capitalize `h` in `GitHub`

data/primitives/overview/releases.mdx
I accidentally [merged this](https://github.com/radix-ui/website/pull/293) into `main`. Just reverted and changed the base branch here.
=> [Release] Add release notes

data/primitives/components/dialog/0.1.3.mdx
We've been asked about how to do this so adding an example to the docs.
=> [Dialog] Add scrollable dialog example

components/demos/RadioGroup.jsx
Reported on discord https://discord.com/channels/752614004387610674/803656831704629298/923239073949302824
=> [RadioGroup] Replace checkbox naming in demo

data/primitives/components/accordion/0.1.5.mdx
Realised this was missing from the props table.
=> [Accordion] Add collapsible prop to docs

data/colors/getting-started/usage.mdx
Fix darkTheme creation based on [stitches docs](https://stitches.dev/docs/theming#add-a-new-theme)
=> Fix darkTheme creation

data/primitives/components/toggle-group/0.1.4.mdx
I feel like I've answered this question a few times now so adding an example to the docs
=> [ToggleGroup] Preventing undefined example

data/primitives/components/radio-group/0.0.1.mdx, data/primitives/components/radio-group/0.0.14.mdx, data/primitives/components/radio-group/0.0.16.mdx, data/primitives/components/radio-group/0.0.19.mdx, data/primitives/components/radio-group/0.0.6.mdx, data/primitives/components/radio-group/0.1.4.mdx, data/primitives/components/toggle-group/0.0.11.mdx, data/primitives/components/toggle-group/0.0.6.mdx, data/primitives/components/toggle-group/0.1.4.mdx, data/primitives/components/toolbar/0.0.14.mdx, data/primitives/components/toolbar/0.1.4.mdx
closes https://github.com/radix-ui/website/issues/330
=> [RadioGroup][ToggleGroup][Toolbar] Fix w3 roving example url

components/Primitives.tsx, components/demos/Select.jsx, components/demos/index.jsx, data/primitives/components/select/0.0.1.mdx, data/primitives/components/select/0.1.0.mdx, lib/primitivesRoutes.ts, package.json, yarn.lock
=> [Select] New primitive docs

components/demos/AlertDialog.jsx, components/demos/AspectRatio.jsx, components/demos/Checkbox.jsx, components/demos/Dialog.jsx, components/demos/RadioGroup.jsx, components/demos/ScrollArea.jsx, components/demos/Switch.jsx, components/demos/Toast.jsx, components/demos/Toggle.jsx, components/demos/ToggleGroup.jsx, components/demos/index.jsx, data/primitives/components/toast/0.0.1.mdx, data/primitives/components/toast/0.1.0.mdx, lib/primitivesRoutes.ts, package.json, yarn.lock
This still needs a demo but covers all the other areas. It'd be good to see if @peduarte is able to create a demo from following these docs when he is back. 
I've added more detail than we usually do in our accessibility and custom API sections.
=> [Toast] New primitive docs

data/primitives/components/toast/0.1.0.mdx
=> [Toast] Fix data-attr format and broken link

data/primitives/components/navigation-menu/0.1.1.mdx
This pull request: Updates documentation or example code
Small catch while I was snooping for that `Select` 😋
=> [Navigation Menu] Fixed typo on installation step

data/primitives/components/navigation-menu/0.1.1.mdx
Adds indicator and usage with router link examples.
=> [NavigationMenu] Add indicator and router link examples

components/demos/NavigationMenu.jsx
Styles the demo indicator to look like an arrow..
=> [NavigationMenu] Style indicator as arrow in demo

components/demos/NavigationMenu.jsx
=> fix: missing slash for stitches.dev

data/primitives/components/toast/0.1.1.mdx
=> Fix closing tag in the Toast documentation

data/primitives/overview/styling.mdx
Update section about extending a primitive to reflect the fact that the types have already [been fixed](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55396).
=> [website/docs] Update extending a primitive regarding fixed types

components/demos/Toast.jsx
fixes https://github.com/radix-ui/website/issues/357
=> [Toast] Fix outline after dismiss

components/demos/DropdownMenu.jsx
=> Add arrow offset to DropdownMenu demo

data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1329
=> Update release note for React 18

components/demos/Accordion.jsx
This pull request fixes a typo Accordion demo component.
=> [radix-ui/website] Fixed typo in Accordion demo

data/case-studies/linear.mdx
Alex asked me to update his title here.
=> Update Linear job title

data/primitives/overview/releases.mdx
Closes #378
@andy-hook, I compared with the package.json installs in the release PR.
=> Fix previous release version numbers in changelog

data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1355
=> Document Select fix

data/primitives/components/navigation-menu/0.1.3.mdx, data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1372
=> Document `NavigationMenu.Link` improvements

data/primitives/overview/releases.mdx
I realised whilst reviewing your docs PR that I had scrolled back a bit too far on mine and inserted 2 items in the previous release.
=> Fix release

data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1392
=> Document ScrollArea animatable Thumb change

data/primitives/components/checkbox/0.1.5.mdx, data/primitives/components/radio-group/0.1.5.mdx
=> [RadioGroup][Checkbox] Remove enter key activation

data/primitives/overview/releases.mdx, package.json, yarn.lock
https://github.com/radix-ui/primitives/pull/1422
=> Document latest RadioGroup change

components/Footer.tsx, components/Header.tsx, components/demos/NavigationMenu.jsx, components/marketing/OtherProductsSection.tsx, pages/case-studies/[slug].tsx
=> Move from icons.modulz.app to icons.radix-ui.com

pages/_app.tsx
=> Remove unused footer

data/primitives/components/select/0.1.1.mdx
Fix Select.ItemIndicator closing element in documentation
=> [Select] fix closing tag in docs example

data/primitives/components/select/0.1.2.mdx, data/primitives/components/toast/0.1.2.mdx
Align release with https://github.com/radix-ui/website/pull/410 and https://github.com/radix-ui/website/pull/411
=> Sync release with base Toast and Select updates

components/demos/Select.jsx, data/primitives/components/select/0.1.2.mdx, data/primitives/overview/releases.mdx, package.json, yarn.lock
https://github.com/radix-ui/primitives/pull/1459
=> Document latest Select changes

data/primitives/overview/releases.mdx, data/primitives/utilities/portal/0.1.5.mdx
https://github.com/radix-ui/primitives/pull/1463
=> Document latest Portal changes

pages/case-studies/index.tsx
=> Fix Case Study application href

data/primitives/components/toolbar/0.1.6.mdx
https://github.com/radix-ui/website/pull/417
=> Parity in release branch from #417

components/demos/Dialog.jsx, data/primitives/components/dialog/0.1.7.mdx
=> Fix Dialog demo labelling

data/primitives/components/toast/0.1.2.mdx, data/primitives/overview/releases.mdx, package.json, yarn.lock
https://github.com/radix-ui/primitives/pull/1469
https://github.com/radix-ui/primitives/pull/1468
=> Document toast animation improvements

pages/colors/index.tsx
=> Remove `Product Hunt` section

components/CssVariablesTable.tsx, components/MDXComponents.tsx, components/PropsTable.tsx, components/marketing/MainHero.tsx, data/colors/palette-composition/understanding-the-scale.mdx, data/primitives/components/accordion/0.1.7.mdx, data/primitives/components/collapsible/0.1.7.mdx, data/primitives/components/context-menu/0.1.7.mdx, data/primitives/components/dropdown-menu/0.1.7.mdx, data/primitives/components/hover-card/0.1.6.mdx, data/primitives/components/navigation-menu/0.1.3.mdx, data/primitives/components/popover/0.1.7.mdx, data/primitives/components/scroll-area/0.1.5.mdx, data/primitives/components/slider/0.1.5.mdx, data/primitives/components/toast/0.1.2.mdx, data/primitives/components/tooltip/0.1.8.mdx
=> Document CSS variables

components/blog/Tooltip.tsx, components/demos/Tooltip.jsx, data/primitives/components/tooltip/0.1.8.mdx, data/primitives/overview/releases.mdx, package.json, yarn.lock
https://github.com/radix-ui/primitives/pull/1490
=> Document tooltip wcag changes

data/primitives/components/dialog/0.1.7.mdx
The scrollable overlay example snippet for dialog had an incorrect import statement
Please let me know if I need to include any additional details in this PR or if I should follow any additional steps in your process.
=> Fix documentation typo for example code in web

data/primitives/components/alert-dialog/0.1.8.mdx, data/primitives/components/context-menu/0.1.7.mdx, data/primitives/components/dialog/0.1.8.mdx, data/primitives/components/dropdown-menu/0.1.7.mdx, data/primitives/components/popover/0.1.7.mdx, data/primitives/components/select/0.1.2.mdx, data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1514
=> Document `allowPinchZoom` changes

data/primitives/components/context-menu/0.0.1.mdx, data/primitives/components/context-menu/0.0.17.mdx, data/primitives/components/context-menu/0.0.19.mdx, data/primitives/components/context-menu/0.0.22.mdx, data/primitives/components/context-menu/0.0.23.mdx, data/primitives/components/context-menu/0.0.24.mdx, data/primitives/components/context-menu/0.0.7.mdx, data/primitives/components/context-menu/0.0.8.mdx, data/primitives/components/context-menu/0.1.0.mdx, data/primitives/components/context-menu/0.1.6.mdx, data/primitives/components/dropdown-menu/0.0.1.mdx, data/primitives/components/dropdown-menu/0.0.17.mdx, data/primitives/components/dropdown-menu/0.0.19.mdx, data/primitives/components/dropdown-menu/0.0.22.mdx, data/primitives/components/dropdown-menu/0.0.23.mdx, data/primitives/components/dropdown-menu/0.0.7.mdx, data/primitives/components/dropdown-menu/0.0.8.mdx, data/primitives/components/dropdown-menu/0.1.0.mdx, data/primitives/components/dropdown-menu/0.1.6.mdx
See https://github.com/radix-ui/website/pull/435
=> Fix typo in `onSelect` description

data/primitives/components/radio-group/0.1.5.mdx
=> Update RadioGroup keyboard navigation docs

data/primitives/components/toast/0.1.1.mdx, data/primitives/components/toast/1.0.0.mdx
=> Fix small typo in Toast

data/primitives/components/dropdown-menu/1.0.0.mdx
Noticed there's a typo in anatomy sample of `Dropdown` component.
=> Fix invalid namespace in Dropdown anatomy

components/demos/Dialog.jsx, data/primitives/components/dialog/1.0.0.mdx
Reference for why I worked on this: https://github.com/radix-ui/primitives/discussions/1234#discussioncomment-3281594
^ is this necessary ?
=> [Dialog] Add example for async form submissions

data/primitives/components/hover-card/1.0.0.mdx
The correct prop name is listed in the sentence before the example.
=> [HoverCard] Correct prop name in example

components/demos/Label.jsx
=> Modernize Label primitive example

data/primitives/components/dropdown-menu/1.0.0.mdx
=> [DropdownMenu] Fix example to pass props to `DropdownMenu.Content`

data/primitives/components/toast/1.1.0.mdx, data/primitives/overview/releases.mdx
Recent changes https://github.com/radix-ui/website/commit/5a7622ecd4b00765c95bc85c5445c4dd1de68dab
Toast `onPause` `onResume` https://github.com/radix-ui/website/commit/c1c9b33417eea291bf5fe58a9503e97ccff54d08
=> Align release notes with latest changes

data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1647
=> Document latest changes

data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1682
=> Document toast timer fix

data/primitives/components/label/2.0.0.mdx, data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1686
=> Document latest Label changes

data/primitives/utilities/slot/1.0.0.mdx
=> Add a section about event handlers in Slot

data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1693
=> Document 1693 changes

data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1695
=> Latest slider updates

data/primitives/components/slider/0.0.1.mdx, data/primitives/components/slider/0.0.17.mdx, data/primitives/components/slider/0.0.5.mdx, data/primitives/components/slider/1.0.0.mdx, data/primitives/components/slider/1.1.0.mdx, data/primitives/overview/releases.mdx
=> Add missing inverted prop to Slider

data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1692
=> Document HoverCard selection improvement

data/primitives/components/radio-group/1.1.0.mdx, data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1530
Change: https://github.com/radix-ui/website/commit/02aea25885fa0fba1e67929dd26642c3131e0a64
=> Document Radio Group `disabled` prop

data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1710
=> [Collapsible][Accordion] Document animation fix

data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1713
=> Latest Slots updates

data/primitives/components/navigation-menu/1.1.0.mdx, data/primitives/overview/releases.mdx
https://github.com/radix-ui/primitives/pull/1716
Change: https://github.com/radix-ui/website/pull/495/commits/6ed8239532a0c83f4d3a8d72d3bcbf351f12ddc1
=> Document `NavigationMenu` delay props

data/primitives/overview/releases.mdx
Account for patch change in Oct 17 release.
=> Adjust release note versions

data/primitives/components/toggle-group/0.0.11.mdx, data/primitives/components/toggle-group/0.1.5.mdx, data/primitives/components/toggle-group/1.0.1.mdx
Closes #463 
**Before**
**After**
=> [ToggleGroup] Improve `orientation` prop description to clarify function

components/HeroCodeBlock.tsx
=> Tweaking styles for new code block

data/case-studies/supabase.mdx
old url: [supabase.io](https://supabase.io)
current url: [supabase.com](https://supabase.com)
=> update supabase url in case studies

data/primitives/components/navigation-menu/1.0.0.mdx, data/primitives/components/navigation-menu/1.1.1.mdx
Just fixes an import statement
=> Fix a typo in Navigation Menu client side routing example

data/primitives/components/popover/1.0.2.mdx
=> Fix `Popover` css demo animation typo in 1.0.2

components/demos/Checkbox/css/styles.css, components/demos/Checkbox/stitches/index.jsx, components/demos/Label/css/styles.css, components/demos/Label/stitches/index.jsx, components/demos/RadioGroup/css/styles.css, components/demos/RadioGroup/stitches/index.jsx, components/demos/Switch/css/styles.css, components/demos/Switch/stitches/index.jsx
See https://github.com/radix-ui/primitives/discussions/1860#discussioncomment-4581760
=> Remove `user-select: none` on `label`

data/primitives/components/scroll-area/0.0.14.mdx, data/primitives/components/scroll-area/0.0.16.mdx, data/primitives/components/scroll-area/0.1.4.mdx, data/primitives/components/scroll-area/1.0.2.mdx
Updated Highlights content to stay consistent with the language used across the documentation. Plus, pops up in searches easier
=> Update Scroll Area features content

components/demos/Menubar/css/index.jsx, components/demos/Menubar/css/styles.css, components/demos/Menubar/stitches/index.jsx, components/demos/index.jsx, data/primitives/components/menubar/0.0.1.mdx, data/primitives/components/menubar/1.0.0.mdx, lib/primitivesRoutes.ts, package.json, yarn.lock
=> Add `MenuBar` docs

data/primitives/overview/getting-started.mdx
=> Fix React import in getting started examples

components/demos/Slider/css/styles.css, components/demos/Slider/stitches/index.jsx, data/primitives/components/slider/1.1.0.mdx
Fix slider styles don't work correctly when orientation is vertical
=> [Slider] Add styles to vertical example

components/demos/Select/css/index.jsx, components/demos/Select/stitches/index.jsx
Just fixed an option in the Select being "leek" instead of "Leek" like all the others.
=> Fix: Typo in Select Demo

components/demos/Popover/tailwind/index.jsx, components/demos/Popover/tailwind/tailwind.config.js
Add Tailwind CSS support to Popover
=> Add Tailwind CSS support to Popover

components/demos/Checkbox/tailwind/index.jsx, components/demos/Checkbox/tailwind/tailwind.config.js
=> [Tailwind]: Add demo for Checkbox

components/demos/AspectRatio/tailwind/index.jsx, components/demos/AspectRatio/tailwind/tailwind.config.js
=> [Tailwind]: Add demo for Aspect Ratio

components/demos/Avatar/tailwind/index.jsx, components/demos/Avatar/tailwind/tailwind.config.js
=> [Tailwind]: Add demo for Avatar

components/demos/HoverCard/tailwind/index.jsx, components/demos/HoverCard/tailwind/tailwind.config.js
=> [Tailwind]: Add demo for Hover Card

components/demos/Progress/tailwind/index.jsx, components/demos/Progress/tailwind/tailwind.config.js
=> Add Tailwind CSS support to Progress

components/demos/RadioGroup/tailwind/index.jsx, components/demos/RadioGroup/tailwind/tailwind.config.js
=> Add Tailwind CSS support to Radio Group

components/demos/ScrollArea/tailwind/index.jsx, components/demos/ScrollArea/tailwind/tailwind.config.js
=> Add Tailwind CSS support to ScrollArea

components/demos/Select/tailwind/index.jsx, components/demos/Select/tailwind/tailwind.config.js
Added the Tailwind CSS example for the Select component. I used arbitrary values to mirror the other examples
=> Add Tailwind CSS support to Select

components/demos/Separator/tailwind/index.jsx, components/demos/Separator/tailwind/tailwind.config.js
=> Add Tailwind CSS support to Separator

components/demos/Slider/tailwind/index.jsx, components/demos/Slider/tailwind/tailwind.config.js
=> Add Tailwind CSS support to Slider

components/demos/Switch/tailwind/index.jsx, components/demos/Switch/tailwind/tailwind.config.js
=> Add Tailwind CSS support to Switch

components/demos/Tabs/tailwind/index.jsx, components/demos/Tabs/tailwind/tailwind.config.js
=> Add Tailwind CSS support to Tabs

components/demos/Toggle/tailwind/index.jsx, components/demos/Toggle/tailwind/tailwind.config.js
=> [Tailwind] Add tailwind demo for Toggle

components/demos/ToggleGroup/tailwind/index.jsx, components/demos/ToggleGroup/tailwind/tailwind.config.js
=> Add Tailwind demo for ToggleGroup component

components/demos/Menubar/tailwind/index.jsx, components/demos/Menubar/tailwind/tailwind.config.js
There are a lot of duplicate items in this one. Would it make sense to abstract the duplicate item classes into variables, or should we leave that up to the consumer?
=> Add Tailwind CSS support to Menubar

components/demos/DropdownMenu/tailwind/index.jsx, components/demos/DropdownMenu/tailwind/tailwind.config.js
Added the Tailwind CSS example for the Dropdown Menu component. I used arbitrary values to mirror the other examples.
=> Add Tailwind CSS support to Dropdown Menu

components/demos/ContextMenu/tailwind/index.jsx, components/demos/ContextMenu/tailwind/tailwind.config.js
=> Add Tailwind CSS support to Context Menu

components/demos/Collapsible/tailwind/index.jsx, components/demos/Collapsible/tailwind/tailwind.config.js
=> Add Tailwind CSS support to Collapsible

components/demos/Toast/tailwind/index.jsx, components/demos/Toast/tailwind/tailwind.config.js
=> Add Tailwind CSS support to Toast

data/primitives/components/navigation-menu/1.1.1.mdx
Corrected the anchor link to the **With client side routing** section in the Navigation Menu documentation.
=> Fix anchor link in `NavigationMenu` content

components/demos/Tooltip/tailwind/index.jsx, components/demos/Tooltip/tailwind/tailwind.config.js
=> [Tailwind]: add demo for Tooltip

components/demos/Dialog/tailwind/index.jsx, components/demos/Dialog/tailwind/tailwind.config.js
=> [Tailwind]: add demo for Dialog

components/demos/AlertDialog/tailwind/index.jsx, components/demos/AlertDialog/tailwind/tailwind.config.js
=> [Tailwind]: add demo for Alert Dialog

components/demos/NavigationMenu/tailwind/index.jsx, components/demos/NavigationMenu/tailwind/tailwind.config.js
=> [Tailwind]: add demo for Navigation Menu

components/demos/Progress/css/index.jsx, components/demos/Progress/stitches/index.jsx, components/demos/Progress/tailwind/index.jsx
=> [Progress] Pass dynamic value in example

components/MDXComponents.tsx, components/PrimitivesDocsPage.tsx, components/demos/Form/css/index.jsx, components/demos/Form/css/styles.css, components/demos/Form/stitches/index.jsx, components/demos/Form/tailwind/index.jsx, components/demos/Form/tailwind/tailwind.config.js, components/demos/Label/css/styles.css, components/demos/Label/stitches/index.jsx, components/demos/Label/tailwind/index.jsx, components/demos/index.jsx, data/primitives/components/form/0.0.1.mdx, lib/primitivesRoutes.ts, package.json, yarn.lock
This PR adds docs for the new `Form` primitive.
=> Add `Form` docs

data/primitives/components/form/0.0.1.mdx
=> Fix typo in form docs

data/primitives/components/alert-dialog/0.0.17.mdx, data/primitives/components/alert-dialog/0.0.19.mdx, data/primitives/components/alert-dialog/0.0.20.mdx, data/primitives/components/alert-dialog/0.1.1.mdx, data/primitives/components/alert-dialog/0.1.7.mdx, data/primitives/components/alert-dialog/1.0.3.mdx, data/primitives/components/dialog/0.0.17.mdx, data/primitives/components/dialog/0.0.18.mdx, data/primitives/components/dialog/0.0.19.mdx, data/primitives/components/dialog/0.0.20.mdx, data/primitives/components/dialog/0.1.0.mdx, data/primitives/components/dialog/0.1.1.mdx, data/primitives/components/dialog/0.1.5.mdx, data/primitives/components/dialog/0.1.7.mdx, data/primitives/components/dialog/1.0.3.mdx, data/primitives/components/dropdown-menu/0.0.17.mdx, data/primitives/components/dropdown-menu/0.0.19.mdx, data/primitives/components/dropdown-menu/0.0.22.mdx, data/primitives/components/dropdown-menu/0.0.23.mdx
=> [Dialog][AlertDialog] Remove legacy id prop from docs

data/primitives/components/toast/0.1.1.mdx, data/primitives/components/toast/1.0.0.mdx, data/primitives/components/toast/1.1.3.mdx
=> Fix typo in toast docs

components/demos/DropdownMenu/tailwind/tailwind.config.js, components/demos/Tooltip/tailwind/tailwind.config.js
[DropdownMenu Sandbox](https://codesandbox.io/p/sandbox/throbbing-architecture-omnqu1)
[Tooltip Sandbox](https://codesandbox.io/p/sandbox/small-darkness-5i43ik)
=> Fix `Tooltip` and `DropdownMenu` `slideRightAndFade` tailwind keyframe

components/HeroCodeBlock.tsx
=> [HeroCodeBlock] Fix invisible text in option

components/demos/Toast/tailwind/tailwind.config.js
https://www.radix-ui.com/docs/primitives/components/toast#duplicate-toasts
=> Remove extra paren in tailwind toast configuration example

data/colors/getting-started/aliasing.mdx
Updates documentation with correct variable syntax.
=> Updates aliasing.mdx with correct variable syntax

data/primitives/components/navigation-menu/1.1.3.mdx
Preview URL: https://radix-website-git-fork-judewang-correct-doc-workos.vercel.app/docs/primitives/components/navigation-menu#viewport
=> Correct data attributes of NavigationMenu.Viewport

data/themes/docs/components/select.mdx, data/themes/docs/components/table.mdx
=> Fix missing dots on some components

pages/themes/playground.tsx
https://discord.com/channels/752614004387610674/803656831704629298/1139393432629039134
=> Fix broken scroll area playground link

data/themes/docs/theme/typography.mdx
=> fix: typos in `Typography` page

data/themes/docs/components/alert-dialog.mdx, data/themes/docs/components/text.mdx, data/themes/docs/theme/breakpoints.mdx, data/themes/docs/theme/color.mdx, data/themes/docs/theme/overview.mdx
=> fix: typos in `Alert Dialog`, `Breakpoints`, `Color`, `Text` and `Overview` pages

pages/primitives/docs/utilities/[...slug].tsx
https://github.com/radix-ui/website/assets/48552260/c197437b-7598-4f05-8a27-0bd9cc2b0be1
=> Fix broken utilities link

data/themes/docs/overview/releases.mdx, package.json, yarn.lock
Upgrade to 1.1.1 and update changelog
=> Upgrade to 1.1.1

data/primitives/docs/components/select/1.2.2.mdx
=> Fix typo in css in Select example

data/themes/docs/theme/token-reference.mdx
=> rename theme-config.css from theme-configs.css

data/primitives/docs/overview/accessibility.mdx
=> Typo accessibility.mdx

components/demos/Accordion/stitches/index.jsx
=> Fix duplicate properties in object literal

data/primitives/docs/guides/server-side-rendering.mdx
=> Add Remix to recommended SSR frameworks

components/Scale.tsx
First time contributor here, I love the project and while using the colors scales today, noticed a small error, so decided to make a possible fix for this
Please let me know if any changes are needed, happy to help in whatever shape possible.
fixes #721 
Fix Video
https://www.loom.com/share/c67b78cc9775424aa691b79c26abbd10?sid=3089f510-b0e5-42fc-8d04-a62af58bc509
=> fix: issue 721: conversion of hex to hsl on scales in colors project

components/Header.tsx, pages/themes/playground.tsx
Closes #706
Before:
https://github.com/radix-ui/website/assets/1539897/108a3a07-75fc-457d-873e-da3ed14cfd98
After:
https://github.com/radix-ui/website/assets/1539897/ce405be9-fbd4-47a2-88a6-dbcf07c6ffb2
=> Fix scroll jumps due to RemoveScroll

data/primitives/docs/utilities/slot/1.0.2.mdx
Syntax error in `Slot` documentation. Added curly bracket
https://www.radix-ui.com/primitives/docs/utilities/slot#event-handlers
=> Fix: Syntax error in Slot documentation.

data/primitives/docs/components/checkbox/1.0.4.mdx
- This repository seems to have no test code
Preview URL: https://radix-website-git-fork-m-shaka-correct-type-workos.vercel.app/docs/primitives/components/checkbox#root
=> correct type of `checked` of Checkbox.Root

data/blog/themes-3.mdx
=> Fix syntax issue in the Themes 3.0 blog post

data/themes/docs/components/heading.mdx
=> refactor(heading): typo, change Text to Heading instead

data/themes/docs/components/select.mdx
Add the commonly requested documentation on preventing an SSR layout shift and rendering an icon in the trigger
=> Radix Themes: Improve Select docs

data/primitives/docs/components/dropdown-menu/2.0.6.mdx
=> Fix link to W3C Menu Button Pattern

data/primitives/docs/components/slider/0.0.1.mdx, data/primitives/docs/components/slider/0.0.17.mdx, data/primitives/docs/components/slider/0.0.5.mdx, data/primitives/docs/components/slider/0.1.4.mdx, data/primitives/docs/components/slider/1.0.0.mdx, data/primitives/docs/components/slider/1.1.2.mdx
=> Fix SliderThumb to SliderPrimitive.Thumb in Abstract Implementation

data/themes/docs/components/theme.mdx
View source link about [Theme](https://www.radix-ui.com/themes/docs/components/theme) is not working.
So I referenced it like below.
- before: https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/theme.tsx
- after: https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/components/theme.tsx
https://radix-website-git-fork-k35o-fix-themes-coponents-91f469-workos.vercel.app/themes/docs/components/theme
=> fix: Radix Themes's coponent/theme sourcePath

components/ThemesPropsTable.tsx
=> fix: Correct the 'radius' theme reference url

data/themes/docs/components/tab-nav.mdx
=> Update tab-nav.mdx / Typo

data/themes/docs/components/radio.mdx
Just radio button instead of radiobutton.
=> Update radio.mdx / Typos

data/primitives/docs/utilities/slot/1.1.0.mdx
Second example under [basic example](https://www.radix-ui.com/primitives/docs/utilities/slot#basic-example) has an undefined variable.
=> Fix example code snippet in `<Slot />` docs

components/ThemesPropsTable.tsx
Fixes the [radix theme issue #513 ](https://github.com/radix-ui/themes/issues/513). Fixed the 404 page link.
=> fix broken link in utilities Theme page

data/colors/docs/overview/installation.mdx
Can be tested in https://radix-website-git-fork-bdsqqq-patch-2-workos.vercel.app/colors/docs/overview/installation
=> docs(colors): Update version listed as latest to 3.0.0

data/colors/docs/overview/usage.mdx
=> Add vanilla-extract usage to colors usage

components/ThemeToggle.tsx, components/marketing/CaseStudiesSection.tsx, pages/primitives/case-studies/[slug].tsx
Adds a few missing accessible names for buttons and avatars. Closes #787 and #788.
=> Add missing accessible names

utils/themesRoutes.ts
=> Add resources link to themes overview nav

components/icons/IconsPanel.tsx
The typo is in the following URL: https://www.radix-ui.com/icons. Please refer to the attached screenshot.
=> fix typo found in `IconsPanel.tsx`

components/demos/Accordion/tailwind/index.jsx
=> Fix Accordion demo in docs

data/themes/docs/components/scroll-area.mdx
=> Fix typo (Scollbars → Scrollbars)

data/primitives/docs/components/one-time-password-field.mdx
=> docs(primitives): fix incorrect name property for `one-time-password-field`

README.md
---
**Description**:  
This PR adds a link to the `.github/CONTRIBUTING.md` file in the `README.md` of the `radix-ui/website` repo. This helps new contributors discover contribution guidelines more easily.
**Fix**:  
Copied the link and text format from the `README.md` in the [`radix-ui/primitives`](https://github.com/radix-ui/primitives) GitHub repo for consistency.
**Related issue**:  
Closes #863
**Test URL**:
https://github.com/radix-ui/website/
=> chore(docs): add link to contribution guidelines

data/primitives/docs/components/password-toggle-field.mdx
=> docs: fix incorrect name property for password-toggle-field
